version: "3.8"

services:
  back:
    image: pss-rh-app-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env.prod
    container_name: pss-rh-app-backend
    restart: always
